name: Stadslab Rotterdam
markdown: kramdown
highlighter: rouge # or rouge or null
exclude: ["node_modules", "gulpfile.js", "package.json"]
collections:
    machines:
      output: true
plugins:
  - jekyll-redirect-from
#baseurl: /stadslabrotterdam